version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build/
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user


hooks:
  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: ec2-user