version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/deploy/
    overwrite: yes

permissions:
  - object: /home/ec2-user/
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: ec2-user
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user