spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: ${FILE_SIZE}
      max-request-size: ${REQUEST_SIZE}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}
  time:
    accessTime: ${JWT_ACCESS_TIME}
    refreshTime: ${JWT_REFRESH_TIME}

gauth:
  clientId: ${GAUTH_CLIENTID}
  clientSecret: ${CLIENT_SECRET}
  redirectUri: ${REDIRECT_URI}

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
    region:
      static: ${S3_REGION}
      auto: false
    credentials:
      access-Key: ${S3_ACCESS_KEY}
      secret-Key: ${S3_SECRET_KEY}
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
