spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: {DB_PLATFORM}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSECRET: ${JWT_REFRESH_SECRET}

gauth:
  clientId: ${GAUTH_CLIENTID}
  clientSecret: ${CLIENT_SECRET}
  redirectUri: ${REDIRECT_URI}

cloud:
  aws:
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET}
      url: ${S3_URL}
    region:
      static: ${S3_REGION}
      auto: false
