name: gcms-backend
app: java@11
options:
  ports: 8080
  env:
    - name: DB_URL
      value: ${{ secrets.DB_URL }}

    - name: DB_PLATFORM
      value: ${{ secrets.DB_PLATFORM }}

    - name: DB_DRIVER
      value: ${{ secrets.DB_PLATFORM }}

    - name: DB_USERNAME
      value: ${{ secrets.DB_USERNAME }}

    - name: DB_PASSWORD
      value: ${{ secrets.DB_PASSWORD }}

    - name: JPA_DDL_AUTO
      value: ${{ secrets.JPA_DDL_AUTO }}

    - name: REDIS_HOST
      value: ${{ secrets.REDIS_HOST }}

    - name: REDIS_PORT
      value: ${{ secrets.REDIS_PORT }}

    - name: JWT_ACCESS_SECRET
      value: ${{ secrets.JWT_ACCESS_SECRET }}

    - name: JWT_REFRESH_SECRET
      value: ${{ secrets.JWT_REFRESH_SECRET }}

    - name: GAUTH_CLIENTID
      value: ${{ secrets.GAUTH_CLIENTID }}

    - name: CLIENT_SECRET
      value: ${{ secrets.CLIENT_SECRET }}

    - name: REDIRECT_URI
      value: ${{ secrets.REDIRECT_URI }}
context:
  git:
    url: https://github.com/GSM-MSG/GCMS-BackEnd.git
    branch: develop
  preset: kotlin