name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
          redis-version: 7
          redis-port: 6379

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew


    - name: Build with Gradle
      run: ./gradlew clean build

