name: GCMS-CD
on:
  push:
    branches: [ "develop" ]

env:
  S3_BUCKET_NAME: gcms-deploy-bucket
  PROJECT_NAME: Gcms-Sever

jobs:
  build:
    name: GCMS-CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Create application.yml on dev
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -i -x test
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name gcms-cd \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name gcms-back-dev \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=gcms-deploy-bucket,bundleType=zip,key=Gcms-Sever/$GITHUB_SHA.zip \
          --region ap-northeast-2 \